version: '3.8'
services:
  nginx:
    build: .docker/nginx
    depends_on:
      - php-fpm
    volumes:
      - .:/app
      - ./.docker/nginx/vhost:/etc/nginx/conf.d
    ports:
      - '${NGINX_HTTP_PORT:-}:80'
      - '${NGINX_HTTPS_PORT:-}:443'
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-http-${COMPOSE_PROJECT_NAME}.rule=Host(`${APP_HOST:-test-app.loc}`)
      - traefik.http.routers.web-https-${COMPOSE_PROJECT_NAME}.rule=Host(`${APP_HOST:-test-app.loc}`)
      - traefik.http.routers.web-https-${COMPOSE_PROJECT_NAME}.tls=true
  php-fpm:
    build: .docker/php-fpm
    depends_on:
      - mariadb
      - redis
    volumes:
      - .:/app
      - ./.docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    labels:
      traefik.enable: "false"
      ofelia.enabled: "true"
      ofelia.job-exec.php-cli.schedule: "@every 1m"
      ofelia.job-exec.php-cli.user: www-data
      ofelia.job-exec.php-cli.command: "php /app/public/cli.php"
  mariadb:
    image: 'mariadb:11'
    ports:
      - '${FORWARD_DB_PORT:-}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-rootpassword}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-dbname}'
      MYSQL_USER: '${DB_USERNAME:-dbuser}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './.docker/mariadb/data:/var/lib/mysql'
    labels:
      - traefik.enable=false
  redis:
    build: .docker/redis
    volumes:
      - ./.docker/redis/data:/data
    ports:
      - '${REDIS_PORT:-}:6379'
    labels:
      - traefik.enable=false
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - php-fpm
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=false

networks:
  web:
    name: traefik_default
    external: true
